/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TrackingSession } from '../../models/tracking-session';

export interface ReadActive$Params {
  tenantId: string;
}

export function readActive(http: HttpClient, rootUrl: string, params: ReadActive$Params, context?: HttpContext): Observable<StrictHttpResponse<(TrackingSession | null)>> {
  const rb = new RequestBuilder(rootUrl, readActive.PATH, 'get');
  if (params) {
    rb.path('tenantId', params.tenantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(TrackingSession | null)>;
    })
  );
}

readActive.PATH = '/tenants/{tenantId}/tracking-sessions/active';
