/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TenantHttpService } from './services/tenant-http.service';
export { ClientHttpService } from './services/client-http.service';
export { DashboardHttpService } from './services/dashboard-http.service';
export { ProjectHttpService } from './services/project-http.service';
export { RecordHttpService } from './services/record-http.service';
export { TaskHttpService } from './services/task-http.service';
