/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Record } from '../../models/record';
import { RecordRequest } from '../../models/record-request';

export interface Upsert$Params {
  tenantId: string;
  uuid: string;
      body: RecordRequest
}

export function upsert(http: HttpClient, rootUrl: string, params: Upsert$Params, context?: HttpContext): Observable<StrictHttpResponse<(Record | void)>> {
  const rb = new RequestBuilder(rootUrl, upsert.PATH, 'put');
  if (params) {
    rb.path('tenantId', params.tenantId, {});
    rb.path('uuid', params.uuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(Record | void)>;
    })
  );
}

upsert.PATH = '/tenants/{tenantId}/records/{uuid}';
