name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - production
  workflow_call:

jobs:
  Production:
    runs-on: deployment
    defaults:
      run:
        working-directory: platform
    environment: production
    steps:
      - name: Checkout production
        uses: actions/checkout@main
        with:
          ref: production
      - name: Define variables
        run: |
          echo "MONGODB_CONNECTION_STRING=${{ secrets.MONGODB_CONNECTION_STRING }}" >> $GITHUB_ENV
          echo "MAIL_CONNECTION_STRING=${{ secrets.MAIL_CONNECTION_STRING }}" >> $GITHUB_ENV
      - name: Define base url
        run: echo "BASE_URL=trackify.kominal.cloud" >> $GITHUB_ENV
      - name: Define stack name
        run: echo "STACK_NAME=trackify_production" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Docker Swarm
        run: docker stack deploy --prune --with-registry-auth -c docker-compose.yml ${STACK_NAME}
