name: Frontend App
on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - frontend-app/**

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-app
    steps:
      - name: Checkout production
        uses: actions/checkout@main
        with:
          ref: production

      - name: Node
        uses: actions/setup-node@main
      - name: Cache node modules
        uses: actions/cache@main
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci --force
      - name: Build
        run: npm run build

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/kominal/trackify/frontend-app
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend-app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  Deployment:
    needs: build
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
