/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PhysicalRiskScenario } from '../models/physical-risk-scenario';
import { TransitionRiskScenario } from '../models/transition-risk-scenario';
export interface DashboardRequest {
  assetId: string;
  period: Array<Date>;
  physicalRiskScenario: PhysicalRiskScenario;
  transitionRiskScenario: TransitionRiskScenario;
}
