/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Project {
  '_id': string;
  clientId: string;
  createdAt: Date;
  createdBy: string;
  name: string;
  tenantId: string;
  updatedAt: Date;
  updatedBy: string;
  uuid: string;
  version: number;
}
