/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Record {
  '_id': string;
  createdAt: Date;
  createdBy: string;
  end: Date;
  start: Date;
  taskId: string;
  tenantId: string;
  updatedAt: Date;
  updatedBy: string;
  userId: string;
  uuid: string;
  version: number;
}
