/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Task {
  '_id': string;
  color: string;
  createdAt: Date;
  createdBy: string;
  name: string;
  projectId: string;
  tenantId: string;
  updatedAt: Date;
  updatedBy: string;
  uuid: string;
  version: number;
}
