/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StoredFile } from '../models/stored-file';
export interface TenantUpdateRequest {
  logo?: StoredFile;
  name: string;
}
