/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StoredFile } from '../models/stored-file';
export interface Tenant {
  '_id': string;
  createdAt: Date;
  createdBy: string;
  logo?: StoredFile;
  name: string;
  updatedAt: Date;
  updatedBy: string;
  uuid: string;
  version: number;
}
